package vinid.vinhome.entities;
// Generated Dec 29, 2019 10:33:01 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcreageHome generated by hbm2java
 */
@Entity
@Table(name = "acreage_home", catalog = "vinid_home")
public class AcreageHome implements java.io.Serializable {

	private Integer acreageHomeId;
	private Acreage acreage;
	private Home home;

	public AcreageHome() {
	}

	public AcreageHome(Acreage acreage, Home home) {
		this.acreage = acreage;
		this.home = home;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "acreage_home_id", unique = true, nullable = false)
	public Integer getAcreageHomeId() {
		return this.acreageHomeId;
	}

	public void setAcreageHomeId(Integer acreageHomeId) {
		this.acreageHomeId = acreageHomeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acreage_id", nullable = false)
	public Acreage getAcreage() {
		return this.acreage;
	}

	public void setAcreage(Acreage acreage) {
		this.acreage = acreage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "home_id", nullable = false)
	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

}
