package vinid.vinhome.entities;
// Generated Dec 29, 2019 10:33:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Building generated by hbm2java
 */
@Entity
@Table(name = "building", catalog = "vinid_home")
public class Building implements java.io.Serializable {

	private Integer buildingId;
	private Status status;
	private String name;
	private int numberFloor;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private Set<AdressHome> adressHomes = new HashSet<AdressHome>(0);

	public Building() {
	}

	public Building(Status status, String name, int numberFloor, Date createdOn, String createdBy, Date modifiedOn,
			String modifiedBy) {
		this.status = status;
		this.name = name;
		this.numberFloor = numberFloor;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
	}

	public Building(Status status, String name, int numberFloor, Date createdOn, String createdBy, Date modifiedOn,
			String modifiedBy, Set<AdressHome> adressHomes) {
		this.status = status;
		this.name = name;
		this.numberFloor = numberFloor;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.adressHomes = adressHomes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "building_id", unique = true, nullable = false)
	public Integer getBuildingId() {
		return this.buildingId;
	}

	public void setBuildingId(Integer buildingId) {
		this.buildingId = buildingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "number_floor", nullable = false)
	public int getNumberFloor() {
		return this.numberFloor;
	}

	public void setNumberFloor(int numberFloor) {
		this.numberFloor = numberFloor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", nullable = false, length = 10)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", nullable = false, length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_on", nullable = false, length = 10)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", nullable = false, length = 100)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "building")
	public Set<AdressHome> getAdressHomes() {
		return this.adressHomes;
	}

	public void setAdressHomes(Set<AdressHome> adressHomes) {
		this.adressHomes = adressHomes;
	}

}
